### PR TITLE
allow only known self signed cert

### LINKED ISSUE #26: Improvement to connections per scanning alerts
Tracking issue for:
- [ ] https://github.com/NASA-PDS/registry-common/security/code-scanning/1

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Allow only known self signed certs

## ⚙️ Test Data and/or Report
Automated unit testing below passes

## ♻️ Related Issues
Closes #26

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

While these are the code changes for accepting a single self signed cert - all it should need - it is not all of the code/system that needs to be changed, The filename for the cert has to now be included in the authorization file (the file that contains the opensearch username and password). It is this single self signed that will be accepted.

Now registry needs to be updated so that the new property is correctly set with filename to the cert it generates.

I do not think these changes matter. The only time self signed is used is during testing and locally in a cluster of docker containers. If I am my own man-in-the-middle attacker than so be it. Self signed should not be used in AWS. In fact, having all the clients with the opensearch cert is just as weak as having TrustAll before changes. If a man-in-the-middle has the client and thus the certs for opensearch, then they can still inject all they want. Point is, no security was added if the certs are not protected in Fort Knox. - non sequitur Did Nixon make that reference obsolete?

**Comment by nutjob4life** [comment]
@al-niessner thanks for the explanation! The Nixon reference was nice too.

Add one or more of us as reviewers and we'll get it approved

**Comment by tloubrieu-jpl** [comment]
Thanks @al-niessner , I will wait to merge the PR since it has impact on other components (as you mentionned registry) and users (I guess we need to update the documentation...)

**Comment by jordanpadams** [comment]
@al-niessner will this update still be needed after your current refactoring?

**Comment by al-niessner** [comment]
@jordanpadams 

No. In fact, this is a really bad request and fix because it makes life way more complicated for benefit. See earlier comment with reference to Nixon.

**Comment by jordanpadams** [comment]
closing this PR for now until the refactoring is complete, at which point we will revisit as needed

**Pull request closed without merging**
