### PR TITLE
NASA-PDS/registry-mgr#122: add capability for list-dd

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Process the hits returned by search and convert them to a list of LddInfo.

## ⚙️ Test Data and/or Report
Run list-dd with -ns cart against ref data:
```
2024-12-12 09:35:28 [INFO ] (RegistryManager.java:<init>:41) Registry URL: app://connections/direct/localhost.xml

Namespace            File                                        Version   Date
-----------------------------------------------------------------------------------------------
PDS4_CART_1F00_1950.JSON null                                           null   2020-12-21T21:48:19Z
```

## ♻️ Related Issues
Closes NASA-PDS/registry-mgr#122

### CODE REVIEW

**Comment by jordanpadams** [comment]
@al-niessner does that output actually make sense?

```
Namespace            File                                        Version   Date
-----------------------------------------------------------------------------------------------
PDS4_CART_1F00_1950.JSON null                                           null   2020-12-21T21:48:19Z
```
Seems like the namespace should be `cart`, File should be `PDS4_CART_1F00_1950.JSON` and version should be the version extracted from the JSON file?

**Comment by al-niessner** [comment]
@jordanpadams 

Yeah, this is where I am confused with yesterday vs today. Yesterday the command loaded just the LDDs that in the DD and changed the attrib_ns to class_ns. I have no idea if that is what it should do or something else is expected today. I think it just looks weird with the title line and just the single LDD.

The other oddity, is namespace being blank. Was it intended that when blank all were returned?

**Comment by jordanpadams** [comment]
@al-niessner I have no idea what the original intent was, but I imagine the list-ldd command was supposed to go through the label(s) and determine the appropriate LDDs from the labels and output that in a list. for above, I would imagine this would be:

```
Namespace            File                                        Version   Date
-----------------------------------------------------------------------------------------------
cart                 PDS4_CART_1F00_1950.JSON                    1.9.5.0   2020-12-21T21:48:19Z
```

The only thing I am not sure of is the version. If it is the LDD version or the PDS4 Information Model version. This version can be found in the JSON file.

**Review by tloubrieu-jpl — APPROVED** [review]
Let's have it in the release today.
Thanks @al-niessner

**Pull request merged**
