### PR TITLE
Baseline refactoring to support OpenSearch Serverless and OpenSearch Java JDK

### LINKED ISSUE #36: Augment authentication behaviour to support Cognito credential set
## 💡 Description
Currently, auth.cfg contains a user/pass set which is passed to OpenSearch as a Basic header.  It is now necessary to support Cognito alongside Basic auth (Basic may be deprecated later).

This will required shoehorning additional functionality into `gov.nasa.pds.registry.common.es.client.EsRestClientBld` (probably).

[See Slack convo for more details](https://jpl.slack.com/archives/C0566EJBGJU/p1684792073753829)

May be smart to depend this issue on https://github.com/NASA-PDS/registry-common/issues/15 if still applicable (it appears so - `registry-commons` is still using an ElasticSearch client)

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Refactored this repo to handle multiple ways of connecting to an open/elastic search service.

## ⚙️ Test Data and/or Report
TBD

## ♻️ Related Issues
Closes #36 
Closes NASA-PDS/harvest#158
Closes NASA-PDS/harvest#127

### CODE REVIEW

**Comment by al-niessner** [comment]
@alexdunnjpl @nutjob4life 

Did the first round of hacking things apart and it all compiles again. Installed a facade for controlling the connection to search. If you either or both of you have some spare cycles, can you take a gander and see if it aligns with what you had in mind. I removed RegistryCfg then started fixing from there. There may be items that somehow still do rather direct connections but I think I found them all by removing RegistryCfg. Still... Anyway, I am just looking for a sanity check.

@jordanpadams @tloubrieu-jpl 

Did you want me to change all of the elasticsearch dependencies to opensearch? I did it for registry way back when so have some experience at it. It will add a day or so but not much.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Here are the changes for the registry connection. Right now I just have a localhost connection but will be adding cognito soon. It should give you a good idea through. For tools that current use --registry https://localhost:9200 it would not be --registry app:/connections/direct/localhost.xml. Here is what that URL now translates into:

https://github.com/NASA-PDS/registry-common/blob/issue_36/src/main/resources/connections/direct/localhost.xml

Should also extend the KnownRegistryConnections tool to extract it as well. Maybe I will do that next while I wait for @sjoshi-jpl 

When extracted, it could be edited and the used with --registry file:/path/to/localhost.xml

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @alexdunnjpl can we do a couple quick smoke tests on this PR along with https://github.com/NASA-PDS/harvest/pull/152 and https://github.com/NASA-PDS/registry-mgr/pull/73

**Review by tloubrieu-jpl — APPROVED** [review]
I've been able to test it, and that works.

**Pull request merged**
